FROM node:lts-alpine
ENV NODE_ENV 'production'
ENV REACT_APP_BENEFITSERVICE_BASE_URL $REACT_APP_BENEFITSERVICE_BASE_URL	
ENV REACT_APP_KEYCLOAK_URL $REACT_APP_KEYCLOAK_URL	
ENV REACT_APP_KEYCLOAK_REALM $REACT_APP_KEYCLOAK_REALM	
ENV REACT_APP_KEYCLOAK_CLIENT_ID $REACT_APP_KEYCLOAK_CLIENT_ID	
ENV REACT_APP_CURAM_PRESCREEN_LINK $REACT_APP_CURAM_PRESCREEN_LINK	
ENV REACT_APP_USER_SERVICE_BASE_URL $REACT_APP_USER_SERVICE_BASE_URL	
ENV REACT_APP_CASESERVICE_BASE_URL $CASESERVICE_BASE_URL
RUN echo $CASESERVICE_BASE_URL
COPY ./ ./
RUN npm install --only=prod && npm run build
FROM nginx
COPY --from=0 build /usr/share/nginx/html
COPY ./nginx/conf.d /etc/nginx/conf.d
