FROM node:lts-alpine
ENV NODE_ENV 'production'
ARG REACT_APP_BENEFITSERVICE_BASE_URL	
ARG REACT_APP_KEYCLOAK_URL	
ARG REACT_APP_KEYCLOAK_REALM	
ARG REACT_APP_KEYCLOAK_CLIENT_ID	
ARG REACT_APP_CURAM_PRESCREEN_LINK	
ARG REACT_APP_USER_SERVICE_BASE_URL	
ARG REACT_APP_CASESERVICE_BASE_URL
COPY ./ ./
RUN npm install --only=prod && npm run build
FROM nginx
COPY --from=0 build /usr/share/nginx/html
COPY ./nginx/conf.d /etc/nginx/conf.d
