export const NETWORK_REQUEST = "NETWORK_REQUEST";
export const NETWORK_RECEIVED = "NETWORK_RECEIVED";
export const NETWORK_REQUEST_FAILED = "NETWORK_REQUEST_FAILED";

export const NETWORK_REQUEST_TYPES = {
  GET: "GET",
  POST: "POST",
  PUT: "PUT",
  DELETE: "DELETE",
};

export const NETWORK_FAILED_REASONS = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  NOT_AUTHORIZED: "NOT_AUTHORIZED",
  NO_NETWORK: "NO_NETWORK",
};
