export const RESOURCE_TYPES = {
  BENEFIT: "BENEFIT",
  BENEFIT_FR: "BENEFIT_FR",
  BENEFITS: "BENEFITS",
  BENEFITS_FR: "BENEFITS_FR",
  QUESTION: "QUESTION",
  QUESTION_FR: "QUESTION_FR",
  QUESTIONS: "QUESTIONS",
  QUESTIONS_FR: "QUESTIONS_FR",
  QUESTIONS_COUNT: "QUESTIONS_COUNT",
  LIFE_JOURNEYS: "LIFE_JOURNEYS",
  LIFE_JOURNEY: "LIFE_JOURNEY",
};
