export const RESOURCE_TYPES = {
  BENEFIT: "BENEFIT",
  BENEFIT_FR: "BENEFIT_FR",
  BENEFITS: "BENEFITS",
  BENEFITS_FR: "BENEFITS_FR",
  BENEFITS_COUNT: "BENEFITS_COUNT",
  LIFE_JOURNEYS: "LIFE_JOURNEYS",
  LIFE_JOURNEY: "LIFE_JOURNEY",
  APPLY_FOR_BENEFIT: "APPLY_FOR_BENEFIT",
  USER_DATA: "USER_DATA",
  REDIRECT_CLIENT_DASH: "REDIRECT_CLIENT_DASH",
};
