export const RESOURCE_TYPES = {
  BENEFIT: "BENEFIT",
  BENEFIT_FR: "BENEFIT_FR",
  BENEFITS: "BENEFITS",
  CASES: "CASES",
  BENEFITS_FR: "BENEFITS_FR",
  BENEFITS_COUNT: "BENEFITS_COUNT",
  LIFE_JOURNEYS: "LIFE_JOURNEYS",
  LIFE_JOURNEY: "LIFE_JOURNEY",
  APPLY_FOR_BENEFIT: "APPLY_FOR_BENEFIT",
};
